---
# RISC OS 64 CI build
#
# The 'release' job is triggered when a tag starting with a 'v' is created,
# which will create a GitHub release for the repository with the name of the
# version tag. The release will be a draft, and should be updated with
# changes as you see fit.
#

name: RISC OS

# Controls when the action will run. Triggers the workflow on:
#   * push on any branch.
#   * tag creation for tags beginning with a 'v'
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  # Pull request events happen on pull request state transitions, so we probably don't want this here.
  pull_request:
    branches: ["*"]

concurrency:
  # Be nice to the build service and only submit a single job at a time.
  group: riscos-build-service
  cancel-in-progress: false

jobs:
  riscos-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Obtain prerequisite build tool
        run: |
          # Fetch the build client
          curl -s -L -o riscos-build-online https://github.com/gerph/robuild-client/releases/download/v0.06/riscos-build-online && chmod +x riscos-build-online

      - name: Run tests on AIF AArch32
        run: |
          tests/run-tests.sh aif32

      - name: Run tests on AIF AArch64
        run: |
          tests/run-tests.sh aif64

      - name: Run tests on modules AArch32
        run: |
          tests/run-tests.sh rm32

      - name: Run tests on modules AArch64
        run: |
          tests/run-tests.sh rm64

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'tests/Test-*.xml'
          comment: true
          group_suite: true
          verbose_summary: true
          detailed_summary: true
          include_passed: true

  progress:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Generate progress data
        run: |
          utils/makestats.pl json > statistics.json

      - name: Generate progress markdown
        run: |
          utils/makestats.pl md > statistics.md

      - name: Report on progress
        run: |
          cat statistics.md >> $GITHUB_STEP_SUMMARY

      - name: Generate plan data
        run: |
          utils/plantogantt.pl > plan.json

      - name: Generate plan mermaid files
        run: |
          utils/plantogantt.pl mmd

      - name: Ensure that Stacks.md hadn't changed
        run: |
          utils/updatestacks.pl
          git diff planning/Stacks.md

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: RISC OS 64 Progress
          path: |
            statistics*
            plan*
